project:
  name: sales-etl-pipeline
  environment: dev

gcp:
  project_id: project-eac6eab1-4acc-46e1-81e
  region: us

storage:
  raw_bucket: sales-raw-data-project-eac6eab1-4acc-46e1-81e
  processed_bucket: sales-processed-data-project-eac6eab1-4acc-46e1-81e
  logs_bucket: sales-logs-project-eac6eab1-4acc-46e1-81e
  temp_bucket: sales-temp-project-eac6eab1-4acc-46e1-81e

input:
  sales_file: gs://sales-raw-data-project-eac6eab1-4acc-46e1-81e/input/sales.csv

output:
  parquet_path: gs://sales-processed-data-project-eac6eab1-4acc-46e1-81e/processed/sales/

bigquery:
  dataset: sales_dw
  table: sales_fact

spark:
  app_name: Sales ETL Pipeline